### ISSUE TITLE
[i18n] inject translations

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn-frontend-account-inbox#3]
Details [here](https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Frontend-Split/Polish/i18n#code-changes-howto-solution-1-kiss)

**Comment by itswillta** [comment]
This is being blocked by https://github.com/OpenPaaS-Suite/esn-frontend-account/issues/10.

**Comment by asmaNode** [comment]
> This is being blocked by [OpenPaaS-Suite/esn-frontend-account#10](https://github.com/OpenPaaS-Suite/esn-frontend-account/issues/10).

Merged
